### ISSUE TITLE
Document the content model

### ISSUE THREAD

**Issue by notS0Solo** [notS0Solo/API-Migration-SWAPI#13]
_As a developer, I want to document the content model that I intend to create in Drupal based on the API data, so that I will have a plan to execute in Drupal._

## Tasks
1. Document the content model that you plan to create in Drupal based on the data schema of the API data.
    - Evaluate data attributes from a relational perspective to determine where multiple content types and/or vocabularies using entity reference might be best.
    - Relationships might already be established if the API has multiple endpoints for different data types.

## Resources
- [Planning your Content Structure (Drupalize.Me)](https://drupalize.me/tutorial/user-guide/planning-structure)
- [Drupal Code Challenges: API Migration: Content Model Template](https://docs.google.com/spreadsheets/d/10HD0LM_qS97yNsBL5wqfjhFyhhjczPbDpbyIEGnbyDc/edit?usp=sharing)
    - This is a more basic version of the one mentioned in [A Specification Tool for Drupal Content Modeling (Acquia)](https://dev.acquia.com/blog/specification-tool-drupal-content-modeling)

**Comment by notS0Solo** [comment]
For this issue I created a Content Model outlining the Content Types, Field Types and Widgets. 

This is the link to the content model.[API Migration Content Model](https://docs.google.com/spreadsheets/d/1AWPFBmu73T1-aN6NtPhJCZsKrb2FZ-WrMM8vM1s_RKk/edit?usp=sharing)

**Comment by weekbeforenext** [comment]
I reviewed the content model and left some comments. It still needs a little more work but it's close.

## Next steps
- Resolve the comments in the content model Google Sheet.

**Comment by notS0Solo** [comment]
Ready for review.

**Comment by weekbeforenext** [comment]
It's looking pretty good. There are still a few comments to address. I also added the alternating row coloring to make it easier to read. 

## Next steps
- Resolve remaining comments.
- Make sure you are consistent with your capitalization of the content types in the help text.
- Make sure all of your help text ends with a period for consistency as well.

**Comment by notS0Solo** [comment]
Ready for review

**Comment by weekbeforenext** [comment]
Looks good to me. This is ready to be executed in Drupal in #17.  Nice work 🚀
